name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-start:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Start application
      run: npm start
